### ISSUE TITLE
Pedidos

### ISSUE THREAD

**Issue by carlosservi** [johnwaves/recambios-express#11]
En la HU #4 indica que tenemos que manejar una serie de pedidos que realizan los clientes. Tal pedido tendrá un identificador único e irá enlazado con un cliente. Posteriormente se le asignará el envío a un repartidor.

**Comment by johnwaves** [comment]
Para esta entidad creo que se podría añadir una variable que represente la lista con las piezas (productos) comprados por el cliente. El resto está genial 👍. Dime también qué te parece lo propuesto cuando puedas.

**Comment by carlosservi** [comment]
He estado revisando esto y pienso que no afecta al modelo de negocio las piezas que incluye el pedido, pero que no tengo problema en crearlo sólo dime sí creamos una entidad producto o un array de texto con el nombre de las piezas. Muchas gracias por el comentario👍👍

**Comment by johnwaves** [comment]
Pues entonces como veas conveniente. Y sí, yo había pensado hacerlo como una lista donde para cada registro hubiese dos campos, uno para el producto y otro para la cantidad del mismo, ¿cómo lo ves? Y gracias a ti por el trabajazo 🤟🤟
