### ISSUE TITLE
Repartidor

### ISSUE THREAD

**Issue by carlosservi** [johnwaves/recambios-express#13]
En la HU #4 indica que tenemos una serie de repartidores a los que se le asignan el envío de los pedidos de los clientes. Tenemos un identificador único para cada repartidor y su horario para que no tengan que trabajar más de sus horas.

**Comment by johnwaves** [comment]
Creo que aquí es necesario almacenar de alguna forma los pedidos asignados a un repartidor, pues un pedido se entrega por un único repartidor pero cada repartidor puede entregar más de un pedido. Lo demás me parece que está bien 👌.

**Comment by carlosservi** [comment]
He incluido una variable pedidos de objetos pedido para incluir los pedidos asignados al repartidor. Cuando puedas revísalo a ver si lo ves bien. Gracias

**Comment by johnwaves** [comment]
> He incluido una variable pedidos de objetos pedido para incluir los pedidos asignados al repartidor. Cuando puedas revísalo a ver si lo ves bien. Gracias

Te he hecho una sugerencia en el código. Lo demás, como te dije ayer, está genial 🤙
