### ISSUE TITLE
Cambiar formato hora en HoraEntrega

### ISSUE THREAD

**Issue by carlosservi** [johnwaves/recambios-express#34]
Poner formato acorde a la hora

**Comment by JJ** [comment]
Este issue no enlaza ninguna HU y tampoco formula un problema. El decir directamente en un issue qué se va a hacer no aporta nada, simplemente retrasa el hacerlo.

**Comment by JJ** [comment]
No cerréis *nunca* desde el interfaz web o vais a tener errores en todas las entregas siguientes.
