### ISSUE TITLE
Actualizar Go a su última versión

### ISSUE THREAD

**Issue by johnwaves** [johnwaves/recambios-express#56]
Para poder cumplir con uno de los requisitos del Objetivo 5, se debe actualizar Go a la última versión disponible.

**Comment by JJ** [comment]
Para empezar, no estás expresando un problema, sino una solución a un problema. Si en issue pones una solución, no estás diagnosticando el problema correctamente, y por tanto la solución que plantees es errónea.
En este caso, no parece razonable que tenga que adaptarse la versión que uses al contenedor. ¿No debería ser al contrario?
También, todos los issues deben relacionarse con alguna HU, aunque sea de forma indirecta.
