### ISSUE TITLE
Elección lenguaje de programación

### ISSUE THREAD

**Issue by carlosservi** [johnwaves/recambios-express#9]
Hola @johnwaves, me han asignado este repositorio para el objetivo 2. Lo primero que tenemos que hacer es ponernos deacuerdo para el lenguaje de programación. ¿Que te parece Typescript?, según los requerimientos que nos comentó el profesor yo creo que puede ser buena opción. Quedo a la espera de saber tu opinión.

**Comment by johnwaves** [comment]
Hola! Bienvenido al proyecto 😄. Por ahora usar TypeScript no me parece mala opción, aunque tal vez resulte un poco complicado entender y manejar errores que puedan aparecer. Yo había pensado en Go (Golang). Dime también qué te parece y ya decidimos.

**Comment by carlosservi** [comment]
Vale perfecto, la idea era usar alguno de esos dos, no tengo preferencias por ninguno, simplemente era para que se adaptara bien a los requisitos. Por tanto confirmame que usamos Go y continúo con el objetivo.

**Comment by johnwaves** [comment]
Genial entonces, elegimos este y a ver qué tal!
